PDLPorters/pdl

Lib/Slatec/slatec.pd
Makefile.PL
t/issue-sf-368.t

See <https://sourceforge.net/p/pdl/bugs/368/>, <https://github.com/PDLPorters/pdl/issues/48>
for more information.

Fix for PDL::Slatec::polyfit() weight dimension mismatch issue

---

.travis.yml

Work in progress - first commit is to get Travis to reproduce the problem. Addresses #81.

Fix Proj4 building on dev EUMM

---

Basic/Core/Dev.pm
Lib/GIS/Proj/Proj.pd
Lib/Slatec/slatec.pd
Lib/Transform/Proj4/Makefile.PL
Lib/Transform/Proj4/Proj4.pd

Fix build to work under dev EUMM

---

.travis.yml
Basic/Core/Dev.pm
Basic/Gen/PP.pm
Basic/MatrixOps/blas.c
Basic/Pod/API.pod
Basic/Slices/slices.pd
Basic/Ufunc/Makefile.PL
Graphics/IIS/pdliisdisp.c
Graphics/TriD/Rout/rout.pd
Lib/GSL/INTERP/gslerr.h
Lib/GSL/SF/gslerr.h

Travis compiler clang fix warnings

---

Basic/Ops/ops.pd
Basic/Primitive/primitive.pd
t/badvalue_scalar_cmp.t

This is to elucidate the issues with stat() and per-PDL badvalues
brought up by Marek Gierliński in SF#390
<http://sourceforge.net/p/pdl/bugs/390/>,
<https://github.com/PDLPorters/pdl/issues/124>.

test comparisons between scalars and 0-dim PDLs with badflag == 1

---

MANIFEST.SKIP
README.md
appveyor.yml

Closes <https://github.com/PDLPorters/pdl/issues/130>.

Add support for the Appveyor CI

---

Demos/Cartography_demo.pm

Just a simple 7-byte change, should be good to go. This fully resolves #137

Set graticule() to scalar context in Cartography demo.

---

Basic/Slices/slices.pd

This was a fix by Craig.  Just processing to merge into master....

Fix sf bug #378 "where on dice of pdl bad results"

---

Basic/Gen/PP.pm
Basic/Pod/Indexing.pod
Basic/Pod/Internals.pod
Basic/Pod/PP.pod

These are all just POD changes.

Pp doc cleanup

---

Basic/Bad/bad.pd
Basic/Ufunc/ufunc.pd

Verify fixes to output type for various *over routines.

Sf340 ufuncover fixes

---

Basic/Ops/ops.pd
t/ops.t

ipow() calculates the integer exponentiation of a value
by successive multiplications.  This allows one to avoid
loss of significance in integer exponents.  pow() converts
the value to double and will always have <52 precision.

Add ipow() method and a test in t/ops.t

---

Basic/Core/Core.pm
Basic/Slices/slices.pd
t/clump.t

Added missing logic for clump(-N) and minor cleanup of
perl wrapper.

Fix sf.net bug 406

---

Example/Fit/lmfit_example.pl
Lib/Fit/LM.pm
t/lm.t

Mostly it is just documentation changes.  However, the new t/lm.t contains sample data copied from Gnuplot, which could potentially raise a license issue.  Check that file please.

Some changes to PDL::Fit::LM

---

Basic/Core/Core.pm
Basic/Core/pdlcore.c.PL
Basic/Core/pdlcore.h.PL
t/constructor.t

Propagate BAD values in constructor calls of the form  '$a=pdl( pdl("BAD,5"),7);'

Badval constructor

---

t/primitive.t

Should be pretty straightforward.

Add tests for fibonacci, which_both, and intersect to primitive.t

---

Makefile.PL

Thanks to Todd Rinaldo for the patch.

Handle @INC without . in it for PDL build

---

appveyor.yml

This needs a look-over to see if any other Windows-related changes need to be made.

Change dmake to gmake on Strawberry Perl (AppVeyor)

---

Basic/Gen/PP.pm
Basic/Ops/ops.pd
MANIFEST
t/ops-bitwise.t
t/ops.t

Improve compatibility with Perl's experimental 'bitwise' feature.

---

.travis.yml
Makefile.PL

Coverage for XS as well

---

Basic/Primitive/primitive.pd

Addresses http://sourceforge.net/p/pdl/bugs/359, https://github.com/PDLPorters/pdl/issues/43.
TODO: add a vsearch tutorial

add vsearch example

---

Basic/Complex/complex.pd
t/complex.t

This is just to run it past the CI. pdl-devel thinks this is ready for prime-time!

Complex atan2

---

.appveyor.yml
IO/FITS/FITS.pm
t/fits.t

Fix wfits so that explicitly setting BITPIX works.

---

Basic/Pod/MATLAB.pod

Add a comparison of vectorised Floyd-Warshall algorithm to MATLAB intro docs.

MATLAB doc tweaks

---

.github/workflows/ci.yml

- Use expression syntax in more places
- Add repo constraint to steps instead of job

GitHub Actions: fix repo constraint for IRC notifications

---

Basic/Primitive/Makefile.PL
Basic/Primitive/primitive.pd
Basic/Primitive/xoshiro256plus.c
Changes
MANIFEST

Primitive::srand() added - fix #350

---

Basic/Core/Basic.pm
Changes
t/basic.t

add tests for sequence-as-instance method bug described in https://github.com/PDLPorters/pdl/issues/370

tests for sequence() as instance method

---

Basic/Core/Core.pm
Changes
t/core.t

Otherwise use workaround.
Fixes <https://github.com/PDLPorters/pdl/issues/374>.

Check to see if pack("D", ...) is available

---

Demos/Demos.pm

Here are some hints which might make it easier for first-time writers of PDL demos (as discussed on IRC)

PDL demos: Add to the documentation how to write a demo

---

Demos/Demos.pm

Mention that new files need to be added to Makefile.PL and MANIFEST,
otherwise the CI actions won't succeed.

More docs for PDL demo creators:  Bookkeeping tasks

---

Libtmp/Minuit/Makefile.PL
Libtmp/Slatec/Makefile.PL
Makefile.PL

It also unifies the pattern in various places.

Fix build on FreeBSD by allowing "amd64"

---

Basic/Core/Core.pm
t/core.t

Wanted this feature and I don't think it breaks anything.

provide access to default info format

---

lib/PDL/IO/Storable.pm

Document that serialisation does not support data flow

---

lib/PDL/Doc.pm

Fixes <https://github.com/PDLPorters/pdl/issues/541>.

Make doc generator reproducible.
