- Basic/Core/Core.pm
- t/issue-sf-367.t
There was a logic error where `->setdims([])` would get called when trying
to remove the outermost dimension, but this would run after using
`clump()` on a string that had a single value and `->dims() == 1`.
This also fixes the BAD value parsing bug in SF#367 which led to an
incorrect BAD value when parsing the string "[BAD]".
See <http://sourceforge.net/p/pdl/bugs/367/>,
<https://github.com/PDLPorters/pdl/issues/47>.
> Fix for string parsing and dimension handling (fixes SF#367)

- Basic/Core/Core.pm
- t/op-eq-warn-for-non-numeric.t
Instead of saying "isn't numeric in null operation", provide a more
descriptive warning that indicates the value and the operator being
used.
See <http://sourceforge.net/p/pdl/bugs/332>,
<https://github.com/PDLPorters/pdl/issues/33> for more information.
> descriptive warning when using the eq overloaded operator on non-numeric strings

- .travis.yml
By default, the Travis-CI helper's `build-dist` command uses Perl 5.20
for running every build run. This simulates a module author releasing a
dist for CPAN with `META.*` files.
By switching that out and running `Makefile.PL` directly, the run uses
the Perl version specific to that run, but it also becomes necessary to
install the `CONFIGURE_REQUIRES` requirements beforehand because the
`META.*` files are not generated yet.
> Travis-CI: set SPLIT_BUILD to false to use the run's version of Perl for configure-time

- Basic/SourceFilter/NiceSlice.pm
This is the original source filter implementation.  The more
correct one using Filter::Simple is too slow.  Work to fix is
underway but postponed for PDL-2.009
> Make Filter::Util::Call the default engine for PDL::NiceSlice

- t/ops.t
This snippet:
```
$INT_MAX=2147483647;
cmp_ok indx($INT_MAX*4)%2, '==', 0, 'big indx modulus';
cmp_ok double($INT_MAX*4)%2, '==', 0, 'big double modulus';
```
It passes on my 64-bit Linux Perl 5.20.1, but on my 64-bit Strawberry Perl 5.20.0 gives these results:
```
```
> t/ops.t fail on 64-bit Strawberry Perl

- .travis.yml
This is in order to test against compilers other than GCC.
This fixes <https://github.com/PDLPorters/pdl/issues/13>.
> Travis-CI: add build that uses Clang as CC compiler

- .travis.yml
- Basic/Ufunc/Makefile.PL
Fixes for building under Clang along with Travis-CI build tweaks that ensure only `clang` is used.
> Travis fix clang

- Basic/Ufunc/Makefile.PL
This fixes the first build problem shown in https://sourceforge.net/p/pdl/mailman/message/34029558/
The second one is from a broken Perl installation, which doesn't have `File::Path` and ignores the prereq stated in `Makefile.PL`.  Really nothing we can or should try to do about that.
> Fix build problem for 2.008 RC3

- Basic/Math/mconf.h
- Basic/Math/quiet_nan.c
- Makefile.PL
It appears that the logic is already in the code,
just that the NANARG determined in mconf.h was not
used to declare the local quiet_nan version.
Works for me, seems simple.  Ok with you?
> Fix to solaris build problem re quiet_nan

- .travis.yml
Contains the safe updates from my CI changes. Some parts aren't fully ready yet, but these are. All of them save time, except for the output-sorting which helps the poor reader comprehend quicker.
> Container-CI work cherry-pick

- Doc/Doc/Perldl.pm
If a user did 'help PDL::IO::Storable' or some other 2-deep module name,
the search for the proper module file from which to display docs
would change the reported location of the docs database (and the documentation head)
in a initialized once-per-pdl-shell variable.  Subsequent searches would
be looking for PDL/IO/IO/Storable.pm, PDL/IO/IO/IO/Storable.pm, etc,
which couldn't be found.  This was due to how foreach aliases the
loop variable to the input array.  Making an explicit copy removes
the aliasing and keeps the variable unchanged.
> Fix sf#396, Module docs can not be found more than once.

- .travis.yml
- appveyor.yml
- t/bigmem.t
This is used to skip `t/bigmem.t` so that it does not die due to an OOM condition.
> Mark CI testing using CI_TESTING environment variable

- Basic/Core/Core.pm
- t/core.t
Verify kmx fix for sf bug #398
> fix for SF#398 "$pdl->hdr items are lost after $pdl->reshape"

- Basic/Ops/ops.pd
biop() routine for code generation was not correct for
operators that do not need to support the $swap argument.
Since that doesn't affect the operator calculation I've
just enable the $swap for all biop() to avoid debugging
a mess of new special cases.
> Fix sf bug 391

- Basic/Core/pdlcore.c.PL
A warning is now given if there is a loss of precision to avoid user surprise.  kmx has pointed out this could be annoying and we may need to make the warning quiet after the first time.  Lets see what shows in the tests on long double systems to see how bad it is.
> make pdl_whichdatatype_double work for NVSIZE > 8

- Basic/PDL.pm
- IO/Storable/storable.pd
Fix SEGFAULT with Storable by adding PDL::IO::Storable to PDL.pm so incorrect usage won't cause a mysterious crash as shown in http://sourceforge.net/p/pdl/bugs/376/ .  This seems a reasonable solution since PDL::IO::Storable is self-contained and needed for Storable to work correctly with PDL.
> sf376 storable segfault

- Basic/Core/Core.xs
- Basic/Core/pdlcore.c.PL
This gives a one time warning that precision will be lost
converting from perl NV to PDL_Doubles.  Removed careful
but useless logic and croak from pdl_whichdatatype_double().
> Move NVSIZE>8 warning to Core.xs BOOT

- t/opengl.t
Simplifying the test to check if the modules can load.
The dynamic window creation tests were convoluted and
were not being skipped correctly which causes false fails
for various platforms.
> Clean up t/opengl.t for testing

- Basic/Core/Core.pm
Thought this had already been checked and merged.
> force new_pdl_from_string to return a piddle with P=physical flag

- Basic/Core/Core.pm
This avoids loss of significance when 64bit PDL_Indx
values are printed.  Part of the 64bit cleanup and polish
for PDL-2.015 (planned for release by Dec 2015)
> Add $PDL::indxformat for PDL_Indx

- Lib/Minuit/Makefile.PL
This fixes a regression introduce by some MacOSX fixes
> Re-add PIC option to 64bit compile

- Basic/Core/Core.pm
- Basic/Primitive/primitive.pd
- t/core.t
- t/primitive.t
This branch clarifies the status of empty piddles by PDL::info (and thus 'help vars' in the shell). Previously empty piddles were listed as PDL->null, which is incorrect.  Now they are listed as their correct type and dimensions (at least one of which is 0). Since which & whichND are used to generate various kinds of empties, I also made sure that whichND returns piddles of the correct type (indx).
> Empty info

- IO/FITS/FITS.pm
1) The NAXIS* keywords were not replaced with their
ZNAXIS* equivalents, so the NAXIS fields in the header were incorrect.
2) The Z*, TFIELDS, TTYPE*, and TFORM* keywords were deleted from
the wronge header object, so the header of the returned piddle
still had those fields present.
> Fix two bugs related to reading RICE-compressed FITS images.

- Basic/Ufunc/ufunc.pd
The operations in Ufunc along a dimension are mostly named
something ending in -over like 'sumover', except for the
cases of routines with names including average, minimum, and
maximum.  This was a cute but surprising set of special cases.
Adding this following equivalent routines:
average       -> avgover
daverage      -> davgover
maximum       -> maxover
maximum_ind   -> maxover_ind
maximum_n_ind -> maxover_n_ind
minmaximum    -> minmaxover
minimum       -> minover
minimum_ind   -> minover_ind
minimum_n_ind -> minover_n_ind
> Add regular {op}over equivalent names

- Basic/Core/Dev.pm
This means eg PDL::IO::GD as an independent module will get pdldoc-ed just like modules in the monolith distro.
> Add PDL::Doc::add_module to pdlpp_postamble

- Basic/Core/pdlcore.c.PL
- t/constructor.t
The changes in <https://github.com/PDLPorters/pdl/pull/188> broke the
build for all cases of `BADVAL_USENAN` xor `BADVAL_PER_PDL`.
This was because the checking for badvalues when copying in
`pdl_kludge_copy_*` did not take into account these variations in
accessing and setting the badvalue.
For example, a simple comparison using `==` is not valid when NaN values are being compared. Here we need to use `!finite(...)` to make the comparison if the type can use NaN values.
Related thread: <http://comments.gmane.org/gmane.comp.lang.perl.pdl.devel/6862>.
> Fixes badval propagation to support all badval configurations

- IO/Misc/misc.pd
- t/misc.t
The code to determine whether the output size agreed with the
format string size was only activated when the format string was
input as the first argument, not in the options hash. This change
activates it for both cases.
Added some tests as well.
> Allow wcols to obey FORMAT option.

- Basic/Core/pdlapi.c
Using %d was causing a compiler warning, %zu should be better.
This probably doesn't warrant a full pull request, but since it's core code, better to be safe.
> Change a printf conversion flag for sizeof().

- Basic/Core/pdlcore.c.PL
- Basic/Pod/FAQ.pod
- Basic/SourceFilter/NiceSlice.pm
- Bugs.pod
- DEVELOPMENT
- Makefile.PL
- README
Building on the excellent work of Derek, and as discussed on the `pdl-devel` mailing list, I believe this covers all of the changes required to transition to using GitHub for PDL development going forward.
I reproduce here my proposed list of needed actions:
I would suggest the intent is already clear, so I have marked some of these done. If everyone is happy with these changes, I would suggest the next stage is merge (which I will do), then Chris can announce code freeze, dev-release, then when he is happy, main-release.
> Change from Sourceforge to GitHub

- Makefile.PL
This is needed e.g. when building with RELRO support.
> Honor LDFLAGS when building pdl.

- Basic/Core/Core.pm
- Basic/Primitive/primitive.pd
The lintian QA tool reported a couple of spelling errors for the PDL 2.019 Debian package build:
* severly  -> severely
* arbitary -> arbitrary
> Fix spelling errors.

- t/fits.t
As reported in #238 the Debian package build of PDL 2.019 failed because the build environment uses a non-existent `$HOME`.
The failure was fixed by only reading & writing the test file if the directory is writable.
Fixes: #238
> Fix tilde expansion tests for environments with non-existent $HOME.

- Basic/Core/Types.pm.PL
Because there was no '=head1 FUNCTIONS' the functions never got
indexed.  Also I added some other POD directives and examples.
> Make functions in Types.pm visible to pdldoc.

- t/slatec-polyfit-weight.t
This makes the test planning consistent between the two slatec
test programs.
> Use Config{WITH_SLATEC} in slatec-polyfit-weight.t startup

- Lib/Transform/transform.pd
- t/transform.t
When using PDL::Transform::map with the 'g' method (pre-calculated
Gaussian sampling), if the inverse transform produced 'NaN' values
in the $idx variable, those NaNs got passed to _map_int as the
SV *map, and after PDL_xform_aux the variable 'tmp' would have
NaNs in it as well. Then in the input accumulation loop, the cp
variable was assigned tmp, which means dd and sum were now NaN.
In that case (sum > GAUSSIAN_MAXVAL) would be (NaN > GAUSSIAN_MAXVAL)
and that always evaluates to false, so essentially the calculation
of alpha would access illegal indices of the gaussian_lookup array.
This would cause a segmentation fault.
This segfault didn't happen for the 'h' method because the condition
if(beta > 0) was false, so the illegal access never happened.
I added a test (replicated for …
> Add logic to avoid segfault in some uses of PDL::Transform::map

- Basic/Constants.pm
- t/constants.t
DEGRAD was not in EXPORT_OK, and had to be called like PDL::Constants::DEGRAD.
> Make PDL::Contants able to export DEGRAD.

- Basic/Lite.pm
- t/lite_loads_twice.t
Sadly, a22a11fb9b2e5527af94fbb3cc39745ef1215f55 actually caused `PDL::Lite` to correctly export functions `pdl` etc, that were no longer being imported. This broke, among other things, `Test::PDL`.
This PR fixes that, with a test to avoid in future.
> Fix PDL::Lite

- Graphics/PGPLOT/PGPLOT.pm
- Graphics/PGPLOT/Window/Window.pm
This warns if PGPLOT is missing when is not installed because optional
dependencies can be skipped at installation. This gives users a clear
notification of why their code will not load.
Mithaldu++ for bringing up the issue on the #pdl IRC
http://irclog.perlgeek.de/pdl/2015-09-15#i_11219756.
CC: @wchristian 
Branch note: This branch is a WIP. It still needs tests and Travis-CI support. Anyone else is welcome to move it forward.
> add a warning if the optional PGPLOT dependency is not available

- Basic/Ops/ops.pd
- t/ops.t
Rebased version of #2. Passes tests.
> Add propagation of badflag with .= (Ops::assgn) for sf.net bug 3543056.

- Basic/Gen/PP.pm
- Basic/Slices/slices.pd
This has the same two commits that were on the original range-speedup branch, which had gone stale and was 400 commits behind master.  I messed up that branch with a rebase gone wrong (note: never start a 400-commit rebase at midnight), so just created this branch and cherry-picked the two commits of interest.
For reference, I ran the following code:
~~~~perl
use strict;
use warnings;
use PDL;
use PDL::NiceSlice;
use Benchmark;
my $im = sequence(1024,1024);
my $indx = random(2,3000)->mult(1023,0)->rint;
timethis (1E5,
sub {$im->range($indx,10,'t');}
);
~~~~
Without these commits I get about 11000 iterations per second, and with the commits about twice that many:
~~~~pre
timethis 100000:  9 wallclock secs ( 9.10 usr +  0.01 sys =  9.11 CPU) @ 10976.95/s (n=100000)
timethis 100000:  5 …
> Range speedup2

- Doc/Doc.pm
- Doc/Doc/Perldl.pm
- Doc/scantree.pl
- Graphics/TriD/POGL/OpenGL.pm
- IO/GD/GD.pd
- Makefile.PL
If this branch were merged into master, nothing would break and usability would be improved.  As is, this accomplishes:
- functions whose name duplicates the name of a function in a different module now show up in the documentation database;
- the 'apropos', 'usage', 'sig', and 'badinfo' documentation helper functions now work with the documentation database's different naming convention
What remains is to account for functions that share documentation.  For example, mzeroes, mones, & msequence in PDL::Matrix all have an entry in the database, but do not appear to have any actual documentation that makes it in.  So doing 'help mzeroes' results in a blank entry.  One must be careful that the change that fixes this does not result in extraneous info in the other cases: using 'help inner' as …
> Fix documentation system

- Basic/Core/Dev.pm
Building PDL::NetCDF failed with:
```
Updating PDL documentation database...
"/usr/bin/perl"  -e 'exit if \$\$ENV{DESTDIR}; use PDL::Doc; eval { PDL::Doc::add_module(q{$mod}); }' --
Scalar found where operator expected at -e line 1, near "$\$ENV"
(Missing operator before $ENV?)
syntax error at -e line 1, near "$\$ENV"
BEGIN not safe after errors--compilation aborted at -e line 1.
```
> Fix pdlpp_postamble oneliner.

- Basic/Core/Makefile.PL
If both of these variables are empty, then the string here would
be just " ", and that would generate a few 'uninitialized' warnings
during 'perl Makefile.PL'. No major problem, but it looks bad.
This sets it to the empty string in that case.
This is a lot of notes for a 12-character addition but since it potentially effects all builds I wanted to have it looked at before pushing to master.
> Squash whitespace-only string in Makefile.PL to quiet EU::MM

- IO/Pnm/Pic.pm
- t/picrgb.t
Add a new exportable subroutine, imageformat, to PDL::IO::Pic, to give access to chkformat, so that a program can find out easily the format of an image file and then check if it can be openend before attempting, avoiding a possible failure.
> Add imageformat to IO::Pnm::Pic to export an access to chkform

- Lib/GSL/INTERP/gsl_interp.pd
- t/gsl_interp.t
Extrapolation seems to have been accidentally allowed by the
GSL interpolation routines. Since GSL v1.15 (released in 2011),
extrapolation returned NaN instead of extrapolating.  These changes
cause the interpolation routines to return an 'input domain error'
if the user attempts to extrapolate.
This should close #279.
> Remove extrapolation code from PDL::GSL::INTERP.

- Makefile.PL
This addresses #285 and fixes build problems seen on both Centos8 with gcc8.3.1 and Fedora32 with gcc 10.2.1, where the final compilation of `pdl` from `pdl.c` fails because the `-fPIC` flag is not in the compile/link command. 
Although comments in the discussion at #285 suggests that this is somehow specific to Centos or Fedora, I very much doubt that to be the case, and suspect it is only due to versions of gcc.    The `Makefile.PL` in current master branch uses
$(CC) $(CFLAGS) $(LDFLAGS) $(CPPFLAGS) pdl.c -o $@
to build `pdl`, but NEITHER (!!) `CFLAGS` nor `CPPFLAGS` is defined in Makefile.PL or Makefile.   `CCFLAGS` is defined, but is rather long and unneeded.  
This fix works to compile and pass tests of Fedora32 and Centos8.  But, again, I believe this is due to the version of gcc, …
> use CCCDLFLAGS for compile of pdl.c to include -fPIC

- IO/FITS/FITS.pm
As identified in issue #288, if a Rice-compressed image had a BLANK
keyword in the FITS header, that would not properly get set to BAD
if the FITS header did not also contain the BSCALE keyword.  This
was because treat_bscale(), which also deals with the BLANKs, was
not called if there was no BSCALE present.
Ideally this change would have a corresponding test, but without
compression in wfits, I don't see how to do it simply.
> rfits properly treats BLANK in rice-compressed images with no BSCALE

- Lib/GSL/DIFF/gsl_diff.pd
- Lib/GSL/SF/gslerr.h
I had the compiler error "implicit declaration of function 'gsl_set_error_handler_off' is invalid in C99"
because we weren't #including gsl_errno.h in some files.  Not sure
why these weren't showing up before!
> Avoid some compilation errors in GSL modules

- .github/workflows/ci.yml
- IO/HDF/Makefile.PL
- IO/HDF/SD/Makefile.PL
- IO/HDF/VS/Makefile.PL
- Makefile.PL
This is for discussion; the first use of a real, working Alien module in the PDL build process. Note that it uses `ExtUtils::Depends` and therefore adds it as a dep.
Consider it a fully-working prototype for considerably tidying up the rest of the build system.
> Use Alien::HDF4 in PDL::IO::HDF build

- Basic/Complex/complex.pd
- Basic/Core/Core.pm
- Basic/PDL.pm
- Basic/Pod/PP.pod
- Changes
I've added a few snippets of documentation in several places. The two commits can be treated as one. 
There are still fundamental design decisions to be made, I think.
- creal, cimag, cabs, carg should cast onto float/double.
- comparison of complex numbers should fail.
In my opinion.
> Doc complex

- Basic/Core/pdlcore.h.PL
- Basic/Pod/Internals.pod
The use of the old PDL API was added in 2002 specifically to backport a
fix for Gimp-Perl <https://github.com/PDLPorters/pdl/commit/cd83ceb6620e36c48b337f2675e7f5048c62e6eb>
so that it could continue to use `PDL->new()` instead of
`PDL->pdlnew()` in the C API.
This makes using that old API an error.
As far as I can tell, Gimp-Perl is the only user of this API. There is
an associated merge request at <https://gitlab.gnome.org/GNOME/gimp-perl/-/merge_requests/1>
which updates Gimp-Perl to the new API.
> Remove PDL_clean_namespace and PDL_OLD_API defines

- .github/workflows/ci.yml
Cygwin CI builds run slowly at the moment and it is not necessary to run
tests on Cygwin for every commit. This will still help catch problems
while not interfering with other builds.
> CI: only run Cygwin build on tag creation (at release time)

- t/core.t
Inf and NaN do not always stringify to the same capitalization on all
versions of Perl (newer versions of Perl do use "Inf" and "NaN"). In
fact, using the C standard library's formatting functions, both would be
in all lower-case:
```c
printf("%f %f\n", INFINITY, NAN); /* C output is "inf nan" */
```
> Use ignore case for testing inf()/nan()

- .github/workflows/ci.yml
So that the IRC log is less cluttered.
> Use shorter commit message in IRC

- .github/workflows/ci.yml
By adding the tag event as a condition to get the build status
for all jobs.
> GHA: Restore cygwin job to build status pre-reqs

- .github/workflows/ci.yml
Adding per discussion in IRC.
This is to address the issue that led to the fix in <https://github.com/pdLPorters/pdl/commit/b8e8f04a1aa4a89a31b1389c351affb3b992f1c0>.
This may be useful in other PDLPorters repos and can be extracted as a target
at a later time.
[Testing the expected build failure](https://github.com/PDLPorters/pdl/runs/3694829628?check_suite_focus=true) by running this change on top of the commit prior to the fix mentioned above:
> GHA: Add step to run make disttest

- Basic/Core/Core.xs
- Basic/Core/pdlcore.c
- Basic/Core/pdlcore.h
- Basic/Primitive/primitive.pd
- Changes
References:
- Helmut G. Katzgraber. "Random Numbers in Scientific Computing:
An Introduction". <https://arxiv.org/abs/1005.4117v1>.
- `Perl_seed()` in the Perl source code.
> Add pdl_seed() function that uses PID and epoch time

- Basic/Primitive/primitive.pd
Perl v5.14.0 introduced a change <https://github.com/Perl/perl5/commit/6f1401dc2acd2a2b85df22b0a74e5f7e6e0a33aa>
that prevents overloading the 'x' (repeat) operator for lists. This
documents the workaround.
Fixes <https://github.com/PDLPorters/pdl/issues/268>.
> Document "x" matmult operator with parentheses for left operand

- Changes
- IO/FlexRaw/t/flexraw_fortran.t
- IO/Pnm/Pic.pm
- IO/t/dumper.t
- Makefile.PL
`File::Which::which()` replaces the ad hoc `inpath()` functions.
> Use File::Which to find executables

- Graphics/PGPLOT/Window/Window.pm
The lintian QA tool reported a POD error for the Debian package build:
```
Around line 1413:
alternative text '/axis option' contains non-escaped | or /
```
> Fix POD errors.

- Changes
- Libtmp/GSL/SF/ellint/gsl_sf_ellint.pd
- Libtmp/GSL/SF/legendre/gsl_sf_legendre.pd
When `gsl-config --version` returns a dotted triple like '2.7.1',
simple parsing like `$version <2.0` does not work.
> Improve version parsing in some GSL modules

- Basic/Core/Core.pm
- Check if quad values can be packed by using `eval`. This is because
the condition for whether `pack` can use quad values is a bit more
complicated. See:
* <https://www.nntp.perl.org/group/perl.perl5.porters/2013/10/msg208380.html>,
* <https://github.com/Perl/perl5/commit/1640b983ff7c1296873ae4dc0e2163160c853cb3>,
* <https://github.com/Perl/perl5/commit/c174bf3bd0aaba83d7aba81b0fbcb0055109a168>
- Add unsigned quad value (Q) to the condition.
> Improve check for packing quad values

- Graphics/Makefile.PL
This separates out the two module requires and version checks, and reports to the user the reason that TriD graphics will not be built.
> Clarify reason for not building TriD graphics.

- Basic/Primitive/primitive.pd
- Changes
- t/primitive.t
This fixes #408.  Not sure if this is the "right" way to fix this, so please review:
About types signatures and `complex`, [PDL::PP](https://metacpan.org/pod/PDL::PP) says _"...If the operation is already complex, there is no effect; if not, the output will be promoted to the type's ["complexversion" in PDL::Type](https://metacpan.org/pod/PDL::Type#complexversion), which defaults to cfloat. Note this is controlled both by the [PDL::Types](https://metacpan.org/pod/PDL::Types) data, and the code in [PDL::PP](https://metacpan.org/pod/distribution/PDL/Basic/Pod/PP.pod)."_
What does _"will be promoted to the type's ["complexversion"](https://metacpan.org/pod/PDL::Type#complexversion)"_ mean?
So if `$y` is complex then `$yi` will be too...but if the caller passes `$y` as real then I would think …
> Add complex support to interpolate(), fixes #408

- .github/workflows/ci.yml
- Changes
- IO/Browser/Makefile.PL
- Makefile.PL
This helps on systems where additional libraries are needed in order to
link against `ncurses`. In particular, this is useful for MSYS2.
> Refactor curses detection to use ncurses*-config

- Basic/Ops/ops.pd
These commits address most, but not all, of the clang compiler warnings that I see with PDL 2.082.  Most have to do with the newly supported datatypes such as (complex) Long Double, and avoids possible truncation-of-value problems.
> Address clang compiler warnings in PDL 2.082

- Demos/Makefile.PL
- Demos/Sound.pm
- MANIFEST
The demo uses PDL to calculate the samples of sine waves in one line, and then passes the "raw" PDL data to an external sound player.
I don't know whether this is good enough for a demo, but for me it was enlightening to see that raw sound can be calculated without looping over Perl arrays, and then directly passed to a sound player.
Since this is my first step with PDL, I'd welcome a review anyway.  I might easily have misunderstood things.
> PDL Demos:  simple demos to prepare sound (sine waves) with PDL

- Basic/Primitive/primitive.pd
- Changes
- t/primitive.t
The new tests all fail, two of them by segfaulting.
This covers GitHub issues #428, #429 and #430, and also an unreported issue that random(1,1,0) segfaults.
> Test some operations with empty ndarrays.

- IO/HDF/SD/SD.pd
As noted in #439, hdf4 4.2.16 removed deprecated aliases which were still used by PDL.
Fixes: #439
> Use malloc/free instead of HDgetspace/HDfreespace.

- Basic/Primitive/primitive.pd
- t/primitive/vsearch.t
> vsearch: fix segv if vsearch $x arg is empty; add support for bad vaues in $vals argument

- Libtmp/Simplex/Simplex.pm
Add a link to the out-of-tree PDL::Opt::ParticleSwarm optimizer.
Also update the broken link from 1998 to chem1.nrl.navy.mil with something that "works" from archive.org
> doc: update SEE ALSO in PDL::Opt::Simplex

- Changes
- Graphics/TriD/OpenGLQ/openglq.pd
Apple has apparently changed the location of glut.h in recent versions of MacOS. This is a small change to get things building again on the platform.
> Fix builds on MacOS Ventura

- Basic/Gen/PP.pm
- Basic/Gen/PP/PDLCode.pm
- Basic/Pod/PP.pod
- Changes
- t/01-pptest.t
Some of `ExtUtil`'s typemaps use the variables `$ALIAS` and `$pname` in their INPUT section. Using e.g.
```
TYPEMAP
my_t   T_HVREF
```
in a `.pd` file won't compile.
Defining `$ALIAS` and setting `$pname` to `$name` from `pp_def` fixes this issue.
Furthermore, the syntax given for embedded typemaps in [perlxs](https://perldoc.perl.org/perlxs#The-TYPEMAP:-Keyword) is specific within XS files. The usage of nested here-documents as specified in [PDL::PP](https://metacpan.org/dist/PDL/view/Basic/Pod/PP.pod#pp_add_typemaps) is not only unnecessary, but will emit a warning if there is neither an INPUT nor an OUTPUT section.
One unrelated fix: An unset `$handlebad` variable causes a warning when `$PP_VERBOSE` is set.
> typemap handling

- Makefile.PL
With this tiny Makefile.PL update, `make coretest` now passes when you’re building PDL using a perl that isn’t in the $PATH.
Without the patch:
```
~/pdl $ ../cpantesting/perl-5.32.0/bin/perl Makefile.PL
Checking if your kit is complete...
Looks good
…
~/pdl $ make test
[all pass]
~/pdl $ make coretest
…
t/ops-bitwise.t ............ Undefined subroutine &Devel::CheckLib::check_lib called at /home/david/pdl/blib/lib/PDL/Core/Dev.pm line 546.
t/ops-bitwise.t ............ Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run
…
```
With the patch:
```
~/pdl $ ../cpantesting/perl-5.32.0/bin/perl Makefile.PL
Checking if your kit is complete...
Looks good
…
~/pdl $ make test
[all pass]
~/pdl $ make coretest
[all pass]
```
> Make sure that `make coretest` uses the right build of perl, and not just whatever's first in the $PATH

- Basic/Pod/PP.pod
Today I managed to get my first PDL::PP module running.  It found the documentation not too easy to read.
The suggested patch moves the Overview to the top, and adds a short section explaining how to operate this module.
I also extended the explanation of the parameters to pdlpp_stdargs.
> Documentation for PDL::PP: Make it easier to get started

- Basic/PDL.pm
- Basic/Pod/DeveloperGuide.pod
- Basic/Pod/FAQ.pod
- Basic/Pod/QuickStart.pod
* Basic/Pod/DeveloperGuide.pod: Delete the sections "Access to PDL's configuration" and "Ingesting an external PDL module". Document $::PP_VERBOSE and $PDL::Graphics::TriD::verbose. Add a section "Generating a Stack Trace" taken from GitHub issue #393. Add some more mappings to the package->source file table.
* Basic/PDL.pm: Link to the Developer Guide under LANGUAGE DOCUMENTATION.
* Basic/Pod/FAQ.pod: Link to the Developer Guide in Q: 3.5.
* Basic/Pod/QuickStart.pod: Link to the Developer Guide. Also remove a phrase "until recently" which was recent ... in 1998, and don't mention HTML copies of the documentation which are no longer generated (and https://perldoc.perl.org exists).
> More stuff for the DeveloperGuide, as suggested in GitHub#481

- Basic/Gen/PP.pm
- Changes
Perl 5 has now simplified the syntax global typemaps.  PDL has copied part of the Perl code and should follow along. The fix has been suggested by @Leont, who also authored the simplification in Perl5.
This fixes #487.
> Fix for the Future: Make PDL build with Perl 5.41 and newer

- Changes
- IO/FITS/FITS.pm
- IO/FITS/t/fits.t
WIP!  This just adds one passing and one failing test illustrating the problem in #488.
> Fix wfits multi-line HISTORY field

- Basic/lib/PDL/Primitive.pd
- Basic/t/primitive-misc.t
- Changes
There was a misterious error according to which complex numbers like i and 5i were considered approximately equal. I corrected the error by putting parenthesis around the macro 
PDL_IF_GENTYPE_REAL(<code if real>, <code if complex>)
->
(PDL_IF_GENTYPE_REAL(<code if real>, <code if complex>) )
I guess something is wrong in the expansion of the macro, but haven't looked at it.
> approx fails for complex values

- lib/PDL/IO/Dumper.pm
- t/dumper.t
* Keep a track of which ndarrays have already been dumped to avoid duplicating them in the dump string.
* Handle multiple refs in the dumper structure.  
* Generalise dumper tests to handle future changes to dump method thresholds.  
Includes some modernisation of code.  More could be done but that's better as a separate PR.  
Fixes #508
> PDL::IO::Dumper: better handling of multiply referenced ndarrays

- Changes
- lib/PDL/Complex/Overloads.pm
- lib/PDL/IO/Storable.pm
- t/storable.t
Tests work with Serial, JSON::MaybeXS, CBOR::XS ~and CBOR::Free~.  (Edit: `CBOR::Free` was a false positive - it does not support FREEZE/THAW).
I also had a look at testing with some of the YAML modules but they do not support FREEZE/THAW callbacks.  
Could probably be squashed into a single commit before merging, thus cleaning up debugging cruft.  
Documentation is still needed.  It should just comprise a note that serialisers that conform to `Types::Serialiser` are (should be) supported.  
I'm not sure where to add it, though, as it does not fit under `PDL::IO::Storable`.  Perhaps its contents could be shifted to a new PDL::IO::Serialisation or similar which is then loaded by default with the rest of PDL.  That might be too large a change, though.
> Add FREEZE and THAW methods for serialisation

- lib/PDL/Ops.pd
- t/ops.t
Added upper_sqrt to take the complex square root of an arbitrary number and choose the branch that lies in the upper half complex plane.
> Add upper_sqrt

- lib/PDL/Dataflow.pod
Added POD code tags to some bare variables in text, e.g. from $y to `$y`
> Dataflow.pod: minor correction to text and added tags

- lib/PDL/Ops.pd
- lib/PDL/Ufunc.pd
- t/ops.t
- t/ufunc.t
Analogous to the other bitwise methods. I don't see a need for _logical_ `xor` as it can easily be emulated using e.g. `(!!$x)->sum % 2`.
> Add bxor and bxorover

- lib/PDL/Ops.pd
- lib/PDL/PP.pm
- lib/PDL/PP.pod
- t/ops.t
- t/pp_pod.t
Please excuse me for being so stubborn and tedious. I become obsessed with an idea too easily.
This patch provides an option `CallFQ` to `pp_def` that makes function calls in the generated POD's usage section fully qualified.
I was merely trying to find out if I could do that. Then it turned out it was much easier than I expected.
> Add option 'NoExport' to pp_def

- lib/PDL/PP.pod
- script/pptemplate
As discussed on IRC:
- Minor bugfix: Requires 'PDL' instead of 'PDL::Basic'
- The script now creates MANIFEST, MANIFEST.SKIP and .gitigignore  files for bookkeeping
- The script writes one line what it does
- POD is adapted to the new "deep" mode results
The second commit recommends pptemplate in the documentation of PDL::PP.
Further ideas:
- The error messages of pptemplate are rather dry.  Using [autodie](https://perldoc.perl.org/autodie) would bring an improvement, but I know that many people are uncomfortable _not_ checking the return code of open etc.
- I did a manual test which could be automated as an xt test:
1 pptemplate PDL:Some:Module
2 cd PDL-Some-Module  
3 git init
4 git status > /tmp/before
5 perl Makefile.PL
6 make
7 make distcheck # should pass, i.e. not mention MANIFEST …
> pptemplate improvements
